- name: import zabbix repository on rhel 7
  yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
- name: install zabbix agent
  yum: name=zabbix-agent
- name: config /etc/zabbix/zabbix_agentd.conf Server
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present  regexp='^Server=' line='Server=172.18.213.243'
  notify:
    - restart zabbix-agent
- name: config /etc/zabbix/zabbix_agentd.conf ServerActive
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present  regexp='^ServerActive=' line='ServerActive=172.18.213.243'
  notify:
    - restart zabbix-agent
- name: config /etc/zabbix/zabbix_agentd.conf Hostname
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present  regexp='^Hostname=' line='Hostname={{ hostname }}'
  notify:
    - restart zabbix-agent
- name: config /etc/zabbix/zabbix_agentd.conf HostMetadata
  lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present insertafter='^# HostMetadata='  line='HostMetadata=autoregister linux {{ meta }}'
  notify:
    - restart zabbix-agent
- name: auto up
  service: name=zabbix-agent enabled=yes state=started